spring.application.name=mamathadigital.com
server.servlet.context-path=/mamathadigital
server.port=8081

#database configurationg
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCL
spring.datasource.username=system
spring.datasource.password=oracle


#hibernate properties
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true	

logging.level.root=INFO

#path of storing images
file.storage.images=D:/mamthadigitalAllImages/userimages/


#Email configuration
spring.mail.protocol=smtp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sujitmaharana6370@gmail.com
spring.mail.password=uzbl tpor mxfl kpps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




